add_lunch_combo pme-userdebug
add_lunch_combo pme-user
add_lunch_combo pme-eng
add_lunch_combo gemini-userdebug
add_lunch_combo gemini-user
add_lunch_combo gemini-eng
add_lunch_combo marlin-userdebug
add_lunch_combo marlin-user
add_lunch_combo marlin-eng
add_lunch_combo h872-userdebug
add_lunch_combo h872-user
add_lunch_combo h872-eng
